# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGeeksforgeeks():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_geeksforgeeks(self):
    self.driver.get("https://www.geeksforgeeks.org/")
    self.driver.set_window_size(1280, 672)
    self.driver.find_element(By.CSS_SELECTOR, ".selected:nth-child(1) > span").click()
    self.driver.find_element(By.LINK_TEXT, "DSA for Beginners").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gfg-nuj-content-sections-data-div:nth-child(2) .gfg-nuj-content-sections-info-desc2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".spinner-loading-overlay:nth-child(26)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".single-chapter-hidden-div-0 > .gfg-nuj-single-track-div:nth-child(1) > .gfg-nuj-single-track-title").click()
  
