# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHOTSTAR():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hOTSTAR(self):
    self.driver.get("https://www.hotstar.com/in/home?ref=%2Fin")
    self.driver.set_window_size(1280, 672)
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_2Kv2J5oCnla5ZQ6pQ65rb_")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-tv-fill").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".icon-tv-fill")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-movies-fill").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_3XVb7IxsFvh7Oy1CvpaF6R")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-sports-fill").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "a > .\\_1CSTLo7uotP5mTlp3jKun7").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
