# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGooglemaptest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_googlemaptest(self):
    self.driver.get("https://www.google.com/maps/@22.2431457,84.9088836,15z?entry=ttu")
    self.driver.set_window_size(1280, 672)
    element = self.driver.find_element(By.ID, "cell1x1")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#cell0x0 > .EmLCAe > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".aoRNLd")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".aoRNLd > img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".hh2c6:nth-child(2) .Gpq6kf").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hh2c6:nth-child(3) .Gpq6kf").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hpLkke:nth-child(2) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".aFsglc:nth-child(1)").click()
  
