# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUgcnettest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ugcnettest(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(1280, 672)
    self.driver.find_element(By.ID, "APjFqb").click()
    self.driver.find_element(By.CSS_SELECTOR, "#Zrbbw > .wM6W7d > span").click()
  
