# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNitristest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_nitristest(self):
    self.driver.get("https://eapplication.nitrkl.ac.in/nitris/Login.aspx")
    self.driver.set_window_size(1280, 672)
    self.driver.find_element(By.ID, "txtUserName").send_keys("223cs3145")
    self.driver.find_element(By.ID, "txtPassword").click()
    self.driver.find_element(By.ID, "txtPassword").send_keys("LCA3DDB11")
    self.driver.find_element(By.ID, "btnLogin").click()
    self.driver.find_element(By.ID, "txtPassword").click()
    self.driver.find_element(By.ID, "txtPassword").send_keys("Tushar@13")
    self.driver.find_element(By.ID, "btnLogin").click()
    self.driver.find_element(By.CSS_SELECTOR, "#messageShow .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mdi-comment-processing").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message-item:nth-child(2) .message-title").click()
  
