# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestZIMBRATEST():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_zIMBRATEST(self):
    self.driver.get("https://mail.nitrkl.ac.in/")
    self.driver.set_window_size(1280, 672)
    self.driver.find_element(By.CSS_SELECTOR, "#zlif__CLV-main__-2388__su > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#zlif__CLV-main__-2387__su > span:nth-child(1)").click()
  
